#pragma once

#include <stdint.h>

#ifndef DEBUG_WEB_ENABLED_DEFAULT
#ifndef NDEBUG
#define DEBUG_WEB_ENABLED_DEFAULT 1
#else
#define DEBUG_WEB_ENABLED_DEFAULT 0
#endif
#endif

#define APP_CONTROL_PORT 4242
#define APP_HTTP_PORT 80

#define APP_CONTROL_HEADER_SIZE 12
#define APP_CONTROL_MAX_PAYLOAD 96
#define APP_CONTROL_RX_BUFFER_SIZE 256

#define APP_HTTP_RX_BUFFER_SIZE 1024
#define APP_HTTP_MAX_BODY_SIZE 256

#define APP_DEFAULT_STA_SSID "DeFord_5"
#define APP_DEFAULT_STA_PASSWORD "jaggedsky483"
#define APP_DEFAULT_AP_SSID "DroneController-Debug"
#define APP_DEFAULT_AP_PASSWORD "benchmode123"

#define APP_DEFAULT_WIFI_CONNECT_TIMEOUT_MS 30000

#define APP_DEFAULT_HEARTBEAT_TIMEOUT_MS 2500
#define APP_MIN_HEARTBEAT_TIMEOUT_MS 250
#define APP_MAX_HEARTBEAT_TIMEOUT_MS 10000

#define APP_DEFAULT_TELEMETRY_INTERVAL_MS 250
#define APP_MIN_TELEMETRY_INTERVAL_MS 50
#define APP_MAX_TELEMETRY_INTERVAL_MS 2000

#define APP_DEFAULT_DEBUG_VERBOSITY 1
#define APP_MAX_DEBUG_VERBOSITY 5

#define APP_BENCH_TIMEOUT_MS 15000
#define APP_BENCH_CONFIRM_TOKEN "BENCH_ENABLE"
#define APP_BENCH_MAX_MOTOR_TEST_THROTTLE_PERCENT 15
#define APP_BENCH_MAX_MOTOR_TEST_DURATION_MS 750

#define APP_LED_TEST_DURATION_MS 250
